//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerExpenseAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expense
    {
        public int EId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int Amount { get; set; }
        public int CId { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
